# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgboundary < Formula
  desc "A wrapper around boundary and pgbouncer CLI for integration into IDE/database tooling"
  homepage "https://github.com/sigterm-de/pgboundary"
  version "0.5.0"

  depends_on "boundary"
  depends_on "pgbouncer"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.0/pgboundary_Darwin_x86_64.zip"
      sha256 "3b815f54eb85b8607b5c8a4b6b081587aee7bfb7cc2e05373e7f0f7b9a887fc9"

      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.0/pgboundary_Darwin_arm64.zip"
      sha256 "7e81b674d31e53215e142280bf136cfdec570efa0f40e80ed9d974964b5c9286"

      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.0/pgboundary_Linux_x86_64.zip"
        sha256 "833e6be79069bd75b249201d3bc9f75f971b1657c89107fa95302ea6798f87ef"

        def install
          # Install the binary into Homebrew's bin directory
          bin.install "pgboundary"

          # Install example configuration files into a documentation directory
          doc.install "pgboundary.ini"
          doc.install "pg_auth"
          doc.install "pg_config.ini"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.0/pgboundary_Linux_arm64.zip"
        sha256 "52832794277196f3a703dffc325451ec7ed8d531923e95f7a240e1e48c4fb403"

        def install
          # Install the binary into Homebrew's bin directory
          bin.install "pgboundary"

          # Install example configuration files into a documentation directory
          doc.install "pgboundary.ini"
          doc.install "pg_auth"
          doc.install "pg_config.ini"
        end
      end
    end
  end

  def caveats
    <<~EOS
      The example configuration file has been installed at:
        #{doc}/pgboundary.ini
        #{doc}/pg_config.ini
        #{doc}/pg_auth
      You may copy and modify it for your use:
        cp #{doc}/pgboundary.ini ~/pgboundary/pgboundary.ini
        cp #{doc}/pg_config.ini ~/pgboundary/pg_config.ini
        cp #{doc}/pg_auth ~/pgboundary/pg_auth
    EOS
  end
end
