# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgboundary < Formula
  desc "A wrapper around boundary and pgbouncer CLI for integration into IDE/database tooling"
  homepage "https://github.com/sigterm-de/pgboundary"
  version "0.5.2"

  depends_on "boundary"
  depends_on "pgbouncer"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.2/pgboundary_Darwin_x86_64.zip"
      sha256 "3fd8657f38cc7bbac8e8b92557565776cb9c3ac99ef9724a93e36b57c2dde567"

      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.2/pgboundary_Darwin_arm64.zip"
      sha256 "add2375ee81113528c9b88f9e56bae1298d1769336073557c4798ed77b3065a1"

      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.2/pgboundary_Linux_x86_64.zip"
      sha256 "5350a7febddcf46766f72c07fafee762cfabb662022aff5967c545eb5736df95"
      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.2/pgboundary_Linux_arm64.zip"
      sha256 "6ed407becb006b398bbccd44a628e0d9d230dea08a71188ad9d7e8f8260addf4"
      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
  end

  def caveats
    <<~EOS
      The example configuration file has been installed at:
        #{doc}/pgboundary.ini
        #{doc}/pg_config.ini
        #{doc}/pg_auth
      You may copy and modify it for your use:
        cp #{doc}/pgboundary.ini ~/pgboundary/pgboundary.ini
        cp #{doc}/pg_config.ini ~/pgboundary/pg_config.ini
        cp #{doc}/pg_auth ~/pgboundary/pg_auth
    EOS
  end
end
