# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgboundary < Formula
  desc "A wrapper around boundary and pgbouncer CLI for integration into IDE/database tooling"
  homepage "https://github.com/sigterm-de/pgboundary"
  version "0.5.3"

  depends_on "boundary"
  depends_on "pgbouncer"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.3/pgboundary_Darwin_x86_64.zip"
      sha256 "2b6218c0349ac03de8e01411c0973abac90b5c813c85a5b9378d82ff87d802a4"

      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.3/pgboundary_Darwin_arm64.zip"
      sha256 "40f27d8c793d4a965275bef890eb44a0a3577b73bc2132c9fca0191a39483f1e"

      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.3/pgboundary_Linux_x86_64.zip"
      sha256 "b39df0d21e6a5d5615453ead1b98360d2acea6ab8f8a40adc419ac3194f6bdc9"
      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sigterm-de/pgboundary/releases/download/v0.5.3/pgboundary_Linux_arm64.zip"
      sha256 "d7d5b45fd019dff59b7173219f54fc7e155b0da4ae146e8add7cd8a7a1149f1e"
      def install
        # Install the binary into Homebrew's bin directory
        bin.install "pgboundary"

        # Install example configuration files into a documentation directory
        doc.install "pgboundary.ini"
        doc.install "pg_auth"
        doc.install "pg_config.ini"
      end
    end
  end

  def caveats
    <<~EOS
      The example configuration file has been installed at:
        #{doc}/pgboundary.ini
        #{doc}/pg_config.ini
        #{doc}/pg_auth
      You may copy and modify it for your use:
        cp #{doc}/pgboundary.ini ~/pgboundary/pgboundary.ini
        cp #{doc}/pg_config.ini ~/pgboundary/pg_config.ini
        cp #{doc}/pg_auth ~/pgboundary/pg_auth
    EOS
  end
end
