# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgboundary" do
  name "pgboundary"
  desc "A wrapper around boundary and pgbouncer CLI for integration into IDE/database tooling"
  homepage "https://github.com/sigterm-de/pgboundary"
  version "0.5.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgboundary"

  on_macos do
    on_intel do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Darwin_x86_64.tar.gz"
      sha256 "11cc4d1a761f90c026d26fab7c139ea4f87c81f97115223b138f36a12f21a353"
    end
    on_arm do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Darwin_arm64.tar.gz"
      sha256 "663c6d62892f48ca105abbaefb26845ee17bf5cd4a2d875322b8dfcca017d8b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Linux_x86_64.tar.gz"
      sha256 "5db435fcee1c4575874fb3eb54bf38bf76fe5e5ac6d497d4e1020e469af7a055"
    end
    on_arm do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Linux_arm64.tar.gz"
      sha256 "a659890469484cd00edbabf723e6dffac72bfba53428b91782332b86c359c1fb"
    end
  end

  caveats do
    "pgboundary requires boundary and pgbouncer to be installed separately:"
    "  brew install boundary"
    "  brew install pgbouncer"
    ""
    "Example configuration files are included in the archive and can be found at:"
    "  #{staged_path}/pgboundary.ini"
    "  #{staged_path}/pg_config.ini"
    "  #{staged_path}/pg_auth"
  end

  # No zap stanza required
end
