# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgboundary" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "0651c9a9a10b71cae849d30ba05e68892ef58d040fb3cc1d51be1a6e5b63b894"
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cd9ca0c59a5b5877a8d9190637509840dde02008fec36c2ef84b2961cd637438"
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb7e6a844b0c966f1b838d352e3eb515e20918f77ecffd31b07a193d80b51603"
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1f806fbdb9705f1a537788598ca1991834754afdb4b2e7107f93621f15f84177"
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Linux_arm64.tar.gz"
    end
  end

  name "pgboundary"
  desc "A wrapper around boundary and pgbouncer CLI for integration into IDE/database tooling"
  homepage "https://github.com/sigterm-de/pgboundary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgboundary"

  # No zap stanza required

  caveats <<~EOS
    pgboundary requires boundary and pgbouncer to be installed separately:
      brew install boundary
      brew install pgbouncer

    Example configuration files are included in the archive and can be found at:
      #{staged_path}/pgboundary.ini
      #{staged_path}/pg_config.ini
      #{staged_path}/pg_auth
  EOS
end
