# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgboundary" do
  name "pgboundary"
  desc "A wrapper around boundary and pgbouncer CLI for integration into IDE/database tooling"
  homepage "https://github.com/sigterm-de/pgboundary"
  version "0.5.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgboundary"

  on_macos do
    on_intel do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Darwin_x86_64.tar.gz"
      sha256 "04a1c8d3bd3437ec5a31bedcf79318e554a2f49af4643e39cb358a50ae12c5a0"
    end
    on_arm do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Darwin_arm64.tar.gz"
      sha256 "e367df04c17a2016eb4ae6164d374b2d645b1fcd7f15f398be473ab84b8cc3d6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Linux_x86_64.tar.gz"
      sha256 "c8a568cb81a5ba7b4bcb28598bd61690befbbed885fb55139e523ac03a0dac9f"
    end
    on_arm do
      url "https://github.com/sigterm-de/pgboundary/releases/download/v#{version}/pgboundary_Linux_arm64.tar.gz"
      sha256 "c93a1c96bca889cadbefc30b54fd2df9342ef9fa236dfeed2c2994a4d797a5aa"
    end
  end

  caveats do
    "pgboundary requires boundary and pgbouncer to be installed separately:"
    "  brew install boundary"
    "  brew install pgbouncer"
    ""
    "Example configuration files are included in the archive and can be found at:"
    "  #{staged_path}/pgboundary.ini"
    "  #{staged_path}/pg_config.ini"
    "  #{staged_path}/pg_auth"
  end

  # No zap stanza required
end
